-- IMPORTAÇÃO DOS DADOS DA TABELA CIDADE:
SELECT * FROM Cidade

INSERT INTO Cidade (Nome, EstadoID)
VALUES 
    ('Curitiba', 1),
    ('Londrina', 1),
    ('Maringá', 1),
    ('Cascavel', 1),
    ('Ponta Grossa', 1),
    ('Foz do Iguaçu', 1),
    ('Guarapuava', 1),
    ('Toledo', 1),
    ('Arapongas', 1),
    ('São José dos Pinhais', 1),
    ('Porto Alegre', 4),
    ('Caxias do Sul', 4),
    ('Pelotas', 4),
    ('Santa Maria', 4),
    ('Gravataí', 4),
    ('Canoas', 4),
    ('Novo Hamburgo', 4),
    ('Viamão', 4),
    ('São Leopoldo', 4),
    ('Rio Grande', 4),
    ('Florianópolis', 5),
    ('Joinville', 5),
    ('Blumenau', 5),
    ('São José', 5),
    ('Chapecó', 5),
    ('Itajaí', 5),
    ('Criciúma', 5),
    ('Lages', 5),
    ('Jaraguá do Sul', 5),
    ('Palhoça', 5),
    ('São Paulo', 2),
    ('Campinas', 2),
    ('Santos', 2),
    ('Ribeirão Preto', 2),
    ('São José dos Campos', 2),
    ('Sorocaba', 2),
    ('Bauru', 2),
    ('Jundiaí', 2),
    ('Piracicaba', 2),
    ('Guarulhos', 2),
    ('Rio de Janeiro', 3),
    ('Niterói', 3),
    ('Nova Iguaçu', 3),
    ('Duque de Caxias', 3),
    ('São Gonçalo', 3),
    ('Petrópolis', 3),
    ('Volta Redonda', 3),
    ('Macaé', 3),
    ('Campos', 3),
    ('Belford Roxo', 3),
    ('Belo Horizonte', 6),
    ('Uberlândia', 6),
    ('Contagem', 6),
    ('Juiz de Fora', 6),
    ('Betim', 6),
    ('Montes Claros', 6),
    ('Ribeirão das Neves', 6),
    ('Uberaba', 6),
    ('Governador Valadares', 6),
    ('Ipatinga', 6),
    ('Cuiabá', 7),
    ('Várzea Grande', 7),
    ('Rondonópolis', 7),
    ('Sinop', 7),
    ('Tangará da Serra', 7),
    ('Cáceres', 7),
    ('Sorriso', 7),
    ('Barra do Garças', 7),
    ('Lucas do Rio Verde', 7),
    ('Alta Floresta', 7),
    ('Campo Grande', 8),
    ('Dourados', 8),
    ('Três Lagoas', 8),
    ('Corumbá', 8),
    ('Ponta Porã', 8),
    ('Naviraí', 8),
    ('Nova Andradina', 8),
    ('Paranaíba', 8),
    ('Aquidauana', 8),
    ('Sidrolândia', 8),
    ('Goiânia', 9),
    ('Aparecida de Goiânia', 9),
    ('Anápolis', 9),
    ('Rio Verde', 9),
    ('Luziânia', 9),
    ('Águas Lindas de Goiás', 9),
    ('Valparaíso de Goiás', 9),
    ('Trindade', 9),
    ('Formosa', 9),
    ('Itumbiara', 9);
